Repository handikatriarlan/hello-world-in-every-language, pull requests merged in 2024-10, with the labels that each got.

#1 Add Hello World in Python
  contributions/python/hello_world.py
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#2 hello world javascript
  contributions/javascript/hello_world.js
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#4 Add Hello World in Erlang
  contributions/erlang/hello_world.erl
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#8 Add Hello World in Fortran
  contributions/fortran/hello_world.f90
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#12 Hello_World added in CPP
  contributions/cpp/hello_world.cpp
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#14 Add Hello World in Scala
  contributions/scala/hello_world.scala
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#15 Add Hello World in golang
  contributions/golang/hello-world.go
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#16 Add Hello World in Rust
  rust/hello_world.rs
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#18 adding hello world in java
  contributions/java/HelloWorld.java
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#19 Hello World in C
  contributions/C/hello_world.c
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#21 Added the hello world code for assembly
  contributions/assembly/hello_world.asm
Labels: enhancement, hacktoberfest-accepted, Review effort [1-5]: 2

#25 Adding Hello World in C# as permitted in PR #24.
  contributions/C#/hello_world.cs
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#29 Adding Hello World in Bash as permitted in PR #28.
  contributions/Bash/hello_world_2.sh
  contributions/Haskell/hello_world.hs
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#30 added hello world in ruby
  contributions/Ruby/hello_world.rb
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#34 Created Hello world in Typescript
  contributions/typescript/hello_world.ts
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#42 Adding Hello World in PHP
  contributions/php/HelloWorld.php
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#43 Creating Hello World in Pascal
  contributions/pascal/hello_world.pascal
  contributions/pascal/helloworld.pascal
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#46 Create hello_world.html
  contributions/html/hello_world.html
Labels: documentation, Review effort [1-5]: 1, hacktoberfest-accepted

#53 Added hello_world in Ada language
  contributions/Ada/hello_world.adb
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#55 Clojure Hello World program
  contributions/clojure/hello_world.clj
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#56 Add hello world in zig
  contributions/zig/hello_world.zig
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#57 Hello world in MATLAB
  contributions/matlab/hello_world.m
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#59 Adding Hello World in Perl as permitted in PR #58
  contributions/Haskell/hello_world.hs
  contributions/Perl/hello_world.pl
  contributions/Swift/hello_world.swift
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#60 Gleam Programming language
  contributions/Gleam/hello_world.gleam
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#64 Create hello_world_2.c
  contributions/C/hello_world_2.c
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#65 Create hello_world.v
  contributions/V/hello_world.v
Labels: documentation, enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#66 added brainfuck language
  contributions/brainfuck/hello_world.bf
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#67 Add Hello World in Malbolge
  contributions/Malbolge/hello_world.mal
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#68 Create hello_world2.py
  contributions/Python/hello_world2.py
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#69 Creating Hello World in SQL
  contributions/SQL/hello_world.sql
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#70 Create hello_world.xml
  contributions/XML/hellow_world.xml
Labels: documentation, Review effort [1-5]: 1, hacktoberfest-accepted

#72 Added HelloWorld.hx file which is written in Haxe programming languange
  contributions/Haxe/HelloWorld.hx
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#74 Create hello_world.apl
  contributions/APL/hello_world.apl
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#75 Create hello_world.v
  contributions/Verilog/hello_world.v
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#76 Added Hello World in Carbon Programming Language
  contributions/Carbon/hello_world.carbon
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#77 Create hello_world.vhd
  contributions/VHDL/hello_world.vhd
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#79 Add Hello World 2 in Cpp
  contributions/C++/hello_world_2.cpp
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#80 Add Hello World 2 in Typescript
  contributions/typescript/hello_world_2.ts
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#81 Add Hello World 2 in Golang
  contributions/Go/hello_world_2.go
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#82 Add Hello World 2 in Kotlin
  contributions/Kotlin/hello_world_2.kt
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#83 helloworld in plsql
  contributions/PLSQL/helloworld.sql
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#85 Add hello world lol code
  contributions/Jakselscript/jakselscript.js
  contributions/LolCode/hello_world.lol
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#89 Added Hello world 2 in javascript
  contributions/Javascript/hello_world2.js
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#91 Add Hello World in bhailang
  contributions/bhailang/hello_world.bhai
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#92 Created Hello World in Ocaml programming language
  contributions/Caml/hello
  contributions/Caml/hello_world.cmi
  contributions/Caml/hello_world.cmo
  contributions/Caml/hello_world.ml
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#94 Create hello_world_3.py
  contributions/Python/hello_world_3.py
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#96 Create hello-world-2.php
  contributions/PHP/hello-world-2.php
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#97 Add ALGOL
  contributions/ALGOL 58/hello_world.alg
  contributions/ALGOL 60/hello_word.alg
  contributions/ALGOL 68/hello_world.alg
  contributions/ALGOL M/hello_world.alg
  contributions/ALGOL W/hello_world.alg
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#100 add hello world in pike
  contributions/Pike/hello_world.pike
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#104 Hello World in Svelte.js
  contributions/svelte/hello_world.svelte
Labels: Review effort [1-5]: 1, hacktoberfest-accepted

#106 Added Hello World in Groovy
  contributions/Groovy/helloworld.groovy
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#107 Add Hello World in Forth
  contributions/Forth/hello_world.fs
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#108 Add Hello World in Ruby
  contributions/Ruby/hello_world_2.rb
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted

#109 Add Hello World in Swift
  contributions/Swift/hello_world_2.swift
Labels: enhancement, Review effort [1-5]: 1, hacktoberfest-accepted
